.vscode/launch.json
server/src/backend/DefinitionProvider.ts
server/src/backend/Macros.ts
server/src/backend/PreprocessorListener.ts
server/src/backend/SemanticTokenCollection.ts
server/src/backend/SourceContext.ts
server/src/backend/SourceMap.ts
server/src/backend/facade.ts
server/src/types.ts

This PR adds fully function macros and macro functions, including nested macros.
The sourcemap is now generated correctly to account for the macro code substitution.

Proper macro support with sourcemap

---

CHANGELOG.md
build.bin.mjs
build.mjs
package-lock.json
package.json
server/src/backend/LpcConfig.ts

make config file jsonc, closes #32

---

CHANGELOG.md
README.md
package.json
server/src/backend/ReferenceProvider.ts
server/src/backend/symbol-utils.ts
server/src/symbols/arrowSymbol.ts
server/src/symbols/efunSymbol.ts
server/src/utils.ts

allow call other source obj to be an array

---

CHANGELOG.md
server/src/compiler/scanner.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/string2.c

String literals should allow newlines in fluffos

---

.vscode/launch.json
CHANGELOG.md
package.json
server/src/backend/LpcConfig.ts
server/src/backend/LpcServer.ts

Fix v1 Issue 80

---

CHANGELOG.md
server/src/compiler/program.ts

do not add global include to lib files, closes #122

---

CHANGELOG.md
server/src/compiler/checker.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/eval1.c

- closes #167
- updates checker to return proper type
- unit test
- changelog update

Return proper type from eval expressions

---

CHANGELOG.md
package.json
server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/array4.c

Parse multidimension array declarations

---

server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/macro3.c

- closes #186
- refactor macro processing code to be more readable
- changelog update

Process macro params before substituting new macros

---

CHANGELOG.md
server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/struct2.c
server/src/tests/cases/compiler/struct4.c

- allow struct params in functions

add LD struct param to parser

---

CHANGELOG.md
server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/macro4.c

Handle array/mapping literals in macro args

---

CHANGELOG.md
server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/closure7.c

Inline closure should allow a statement in the body

---

CHANGELOG.md
server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/class2.c
server/src/tests/cases/compiler/class4.c

parser should not treat class as a reserved word in LD

---

CHANGELOG.md
server/src/compiler/parser.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/return1.c

- closes #261
- add unit test return1

disable return node ASI

---

CHANGELOG.md
server/src/compiler/binder.ts
server/src/compiler/checker.ts
server/src/compiler/types.ts

add symbols for new class & properties in initializer

---

CHANGELOG.md
server/src/compiler/parser.ts
server/src/compiler/types.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/namedObject6.c
server/src/tests/cases/compiler/object.c
server/src/tests/cases/compiler/object2.c

Fix parsing of union types with named object members

---

CHANGELOG.md
server/src/compiler/checker.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/flowType3.c

- closes #190
- add unit test flowType3.c

Fix flow type when decl is object array

---

CHANGELOG.md
server/src/compiler/types.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/defineUndefined.c

- closes #272
- add unit test definedUndefined.c

make `undefined` not a reserved word

---

CHANGELOG.md
server/src/lpcserver/server.ts

handle undefined workspace path

---

CHANGELOG.md
server/src/compiler/factory/nodeFactory.ts
server/src/compiler/parser.ts
server/src/compiler/types.ts
server/src/tests/__snapshots__/compiler.spec.ts.snap
server/src/tests/cases/compiler/mappingType1.c
server/src/tests/cases/compiler/mappingType2.c

feat: add MappingTypeNode and related parsing and factory functions
