jlchmura/lpc-language-server

CHANGELOG.md, package.json, server/src/backend/DetailsVisitor.ts
Fixes #56 
- Display correct string for mapping types in function signatures.
Enhancement:
- Identifier strings are now interned to reduce memory.
=> fix missing mapping type in signature. also intern strings #56

.vscode/launch.json, CHANGELOG.md, client/src/configuration/configuration.node.ts, client/src/configuration/configuration.ts, client/src/extension.ts, package.json, server/src/compiler/diagnosticInformation.ts, server/src/compiler/parser.ts, server/src/compiler/scanner.ts, server/src/lpcserver/server.ts, server/src/server/scriptInfo.ts
The server will now run with a default max heap size of 3072.  The user can change this using the `LPC.languageServer.maxLpcServerMemory` setting in vscode preferences.
This change was made to address #121
=> Memory improvements

CHANGELOG.md, syntaxes/lpc.tmLanguage.json
Update the language syntax so that property access tokens (`.` and `->`) will still be captured when there is whitespace between that token and the function name.
Example
```c
obj->   foo();
```
=> Syntax highlighting should allow whitespace after property access tokens

CHANGELOG.md, build.mjs, server/src/compiler/checker.ts, server/src/compiler/types.ts
This PR modifies signature resolution to prefer an override with LPCDoc.  If both the function and forward define have a doc comment, this function will be prefered.
=> Prefer override with LPCDoc comment

CHANGELOG.md, server/src/compiler/checker.ts, server/src/compiler/utilities.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/inherit1.base1.c, server/src/tests/cases/compiler/inherit1.base2.c, server/src/tests/cases/compiler/inherit1.c
This PR fixes a problem where sefun inherited members were not being added to the globals table. This caused them to be inconsistently resolved.
This PR closes #144.
=> Add sefun inherited members to globals

CHANGELOG.md, server/src/compiler/resolutionCache.ts, server/src/server/editorServices.ts, server/src/server/project.ts, server/src/server/session.ts, server/src/services/services.ts, server/src/services/types.ts
This PR does two things to close #143 :
1) Enables the resolution cache, which wasn't being used before.
2) Uses the data in the resolution cache to find files that are dependent on a source file.  This information is used to trigger a re-parse of those files. Currently this only happens when editing an `.h` file.
=> Trigger re-parse of files that include the file being edited.

CHANGELOG.md, package.json, server/src/compiler/checker.ts, server/src/compiler/parser.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/indexAccess2.c
When parsing an index access inside another expression that has disallowed commas (such as a prefix unary), the parser needs to run outside the DisallowComma context for index access so that it can properly parse its comma expression.
=> Allow comma expr inside index access

efuns/fluffos/objects.h, efuns/fluffos/zh-cn/objects.zh-cn.h
Update fluffos efun::present definition for the optional second parameter. If not provided, it defaults to `this_object()`, per the efun docs:
```c
* if  first  argument  is  object, second argument is missing, check if
* object is in this object's inventory, or as a sibling in this  object's
* environment's inventory, returns object's parent.
```
=> update fluffos efun::present for optional second parameter

CHANGELOG.md, package.json, server/src/compiler/binder.ts, server/src/compiler/checker.ts, server/src/compiler/emitter.ts, server/src/compiler/parser.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/forEach8.c, server/src/tests/cases/compiler/forEach9.c
Fixes #161 where the iterator type in a foreach was always being assigned a string even though it should have been a resolved object.
=> Use proper array element type in foreach statements

efuns/fluffos/contrib.h, efuns/fluffos/zh-cn/contrib.zh-cn.h
Update fluffos efun::query_num definition for the optional second parameter. If not provided, it defaults to 0.
```
string query_num(int num, int many: 0);
Converts `num` into a string representation. If `many` is greater than 0
and `num` is greater than `many`, the resulting string is "many".
Any `num` greater than 99,999 is always "many", the same for any `num` less
than 0.
```
=> update fluffos efun::query_num for optional second parameter

efuns/fluffos/system.h, efuns/fluffos/zh-cn/system.zh-cn.h
Update fluffos::shutdown definition for the optional parameter. If not provided, it defaults to `0`.
=> update fluffos efun::shutdown for optional parameter

CHANGELOG.md, server/src/compiler/parser.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/class3.c
- allows struct/class property declarations to contain a list of names
- closes #188
- changelog update
=> parse property signature name list

CHANGELOG.md, server/src/compiler/scanner.ts, server/src/lpcserver/server.ts, server/src/tests/cases/compiler/array5.c
Scanner should allow whitespace between open paren and brace/bracket for the start of literal arrays and mappings
=> Scanner should allow whitespace in array/mapping literal

CHANGELOG.md, lib/package.json, package.json, server/src/compiler/checker.ts, server/src/compiler/parser.ts, server/src/compiler/utilities.ts, server/src/lpcserver/server.ts, server/src/server/session.ts, server/src/server/types.ts, server/src/services/services.ts
When editing a file that has been "imported" into other files via an `#include` directive, 
the server will not only invalidate dependent files (that is, those that include the file being edited) under two conditions:
1) if the dependent file is open in the editor
2) there are less than 25 files dependent on the include.
If those two conditions are not met, then the dependent files will be in a stale state until they are opened and an edit is made, which drastically improves performance - especially when editing a global include.
=> Perf Improvement when editing included files

CHANGELOG.md, package.json, server/src/compiler/scanner.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/mapping6.c
- closes #202
- add unit test for #202
- changelog update
- bump version to 1.1.29
=> Allow newline whitespace in array/mapping literals

server/src/compiler/parser.ts
- Pretty much any file in mg-mudlib would cause this. The parser was not removing include files from its dependency graph after they were parsed.
- A diagnostic is no longer reported for circular includes since the drivers will just ignore these.  A log entry is written to the language server log instead
=> Fix parser incorrectly reporting circular include

CHANGELOG.md, server/src/compiler/checker.ts, server/src/compiler/parser.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/array6.c, server/src/tests/cases/compiler/array7.c
- closes #203
- adjust parser to allow * without type
- adjust type checker to return autoArray when no type node is provided
=> declarations can have array with not element type

CHANGELOG.md, server/src/compiler/checker.ts, server/src/compiler/factory/nodeFactory.ts, server/src/compiler/parser.ts, server/src/compiler/types.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/catchBlock4.c
- closes #207 
- add mofier to catch statement parsing and AST node
=> Allow modifiers in catch statements

CHANGELOG.md, server/src/compiler/parser.ts, server/src/tests/__snapshots__/compiler.spec.ts.snap, server/src/tests/cases/compiler/forEachRef2.c
=> Allow `&` in an LD foreach expression

CHANGELOG.md, server/src/compiler/checker.ts, server/src/compiler/types.ts, server/src/compiler/utilities.ts, server/src/server/session.ts, server/src/services/services.ts, server/src/services/signatureHelp.ts, server/src/services/symbolDisplay.ts, server/src/services/types.ts
-   [Feat: get it to stop counting forward declaration as an overload #229](https://github.com/jlchmura/lpc-language-server/issues/229)
-   Fix: Display `mapping` keyword instead of global mapping symbol name.
-   Fix: Function return type was not displayed in completions detail.
-   Fix: Signature help return type should be LPC-style, not TypeScript.
=> Signature Help, Completion, and Hover formatting fixes

CHANGELOG.md, efuns/fluffos/interactive.h, efuns/fluffos/zh-cn/interactive.zh-cn.h
- closes #244
- varargs version of efun will be used instead
=> remove deprecated enabled_commands(void)
